### ISSUE TITLE
Hangs with Eclipse Kepler in combination with OpenJDK 7 update 40 build 43

### ISSUE THREAD

**Issue by jschwartzenberg** [alexkasko/openjdk-unofficial-builds#18]
I installed OpenJDK 7 update 40 build 43 AMD64 on Windows 7 in combination with Eclipse Kepler. Eclipse starts up and I am able to import a project, but quickly after that Eclipse completely hangs and I have to kill the program.

This does not happen with Oracle JDK 7 update 51.

I haven't tried 'OpenJDK 7 update 45 build 31 (IcedTea 2.4.3)' (I only noticed it just now). What exactly is the difference between these OpenJDK 7 releases?

**Comment by alexkasko** [comment]
Won't have cycles to investigate this, closing as eclipse specific.
