### ISSUE TITLE
Virus detected in OpenJDK 6 installer

### ISSUE THREAD

**Issue by Petrouchka** [alexkasko/openjdk-unofficial-builds#20]
Hello,

AVG detects a virus in install.jar (in https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.6.0-unofficial-b31-windows-i586-installer.zip and in https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.6.0-unofficial-b31-windows-amd64-installer.zip) :
https://www.virustotal.com/fr/file/208234ef7133c76184f0232099a227415c79d233c99b5962c5bfaaca469a9931/analysis/1413112865/
https://www.virustotal.com/fr/file/958b0f993d956ba222d9400ec074aa06a071cb8b221705bfb6844f9005ea467b/analysis/1413120803/

How OpenJDK is compiled ? Are you using a fresh install of Windows+compiler with original DVD, without installing nothing else downloaded on internet ? (by exemple, using a snapshot in VirtualBox or something similar) ? Viruses can come from mails, downloading something on internet or just connecting an USB key and they can be very very furtive.

**Comment by alexkasko** [comment]
I ran all the 7u80 binaries (except linux-amd64-debug that is too big) agains virustotal, all of them are clean (some antiviruses are not finished yet though):

 - https://www.virustotal.com/en/file/b87beb73f07af5b89b35b8656439c70fb7f46afdaa36e4a9394ad854c3a0b23d/analysis/1431878390/
 - https://www.virustotal.com/en/file/cfae491f645a5320111c5264b0fc997ffb29cc4da017879629e52dc170a01a20/analysis/1431878539/
 - https://www.virustotal.com/en/file/8358b6b585b73c2a6def9fe0b9fde7ecdaa1acc9387ef06c90ffb0d3d5ae577d/analysis/1431878658/
 - https://www.virustotal.com/en/file/2dafc91c91bd088a9d39528c3c29f44024aa10e5863db0f6d76b03b95a2f2917/analysis/1431878742/
 - https://www.virustotal.com/en/file/af3b028dc4920bcdf9a9518e206c18eb79c7ad1e1f53f4ae9f16bf7499c8cd80/analysis/1431878838/
 - https://www.virustotal.com/en/file/9e4d5cd9aaba02c480b561148a4df7f140caf15d23c8fcd7f65d6bf3520aba82/analysis/1431878918/
 - https://www.virustotal.com/en/file/3816ec739423fff2a801086c05a7ece36151f31b8b9810c120de8df251cd4a23/analysis/1431879913/
 - https://www.virustotal.com/en/file/aa778605e3554270afd1f3ff2f45c2543792f459f68e6518df71f94529ca5785/analysis/1431880029/
 - https://www.virustotal.com/en/file/f6df07cec3b1bd53b857e5f4e20309ab5e8aeaa29ca9152ab0d26b77b339780a/analysis/1431880114/
 - https://www.virustotal.com/en/file/8cd39f311b2481ce36038f6a1d93d50d3f9fd130383a14064a215171af93551f/analysis/1431880315/
 - https://www.virustotal.com/en/file/ce65c394be486aeef5c3d2e30a3d9eac9264c5a7564844ae26c66f4aca98fc52/analysis/1431880538/
 - https://www.virustotal.com/en/file/1b835601f4ae689b9271040713b01d6bdd186c6a57bb4a7c47e1f7244d5ac928/analysis/1431880782/
 - https://www.virustotal.com/en/file/8b4b7ea52db6a860d9d7dd9fe8057804da0506b7136bf27143fac8abeb54cdf7/analysis/1431881695/
 - https://www.virustotal.com/en/file/5b938309099b948960d5f34e51fa1d409621b5df3cf219f1e98b144684f42165/analysis/1431881837/
 - https://www.virustotal.com/en/file/f3b715bc049b3c88bc47695278433c7dc4b2648e2b156f5e24346aecba343035/analysis/1431881995/
 - https://www.virustotal.com/en/file/f8fd48fcf2a8d790d23ca86ada4a258a371a8c6c28df9b99b1e075dba3913cd9/analysis/1431882075/

This is the best I can do, I'll close this issue as I won't have cycles to investigate it further.
