### ISSUE TITLE
GlobNote doesn't start with OpenJDK

### ISSUE THREAD

**Issue by Petrouchka** [alexkasko/openjdk-unofficial-builds#21]
I installed openjdk-1.6.0-unofficial-b31-windows_32-bits in Windows XP Pro and then GlobNote 1-4.
http://globonote.info. I checked all the check boxes when installing OpenJDK.
When I start GlobNote, it doesn't find OpenJDK, see error message in joined file
![capture](https://cloud.githubusercontent.com/assets/3955499/5392792/8f7debc0-812a-11e4-967b-3079bc164647.png)
.

**Comment by alexkasko** [comment]
Won't have cycles to investigate this, closing as launch4j specific.
