### ISSUE TITLE
will openJDK work for java EE?

### ISSUE THREAD

**Issue by bhavyamanasa** [alexkasko/openjdk-unofficial-builds#22]
hi,
 I am new to openJDK. 
i recently downloaded openJDK-1.7.0-u60-unofficial-windows-amd64-installer.

i am using windows 8.1

it is working fine with java SE, but got struck for java EE. i am unable to edit things in my project, it is showing as not responding.

can you give me solution for this as soon as possible.

Thanks in advance.

**Comment by bhavyamanasa** [comment]
thanks for no answer!!

i got the solution, and i am working perfectly in java EE with openjdk in windows

**Comment by alexkasko** [comment]
Yes, OpenJDK should work for Java EE too, closing this issue.
