### ISSUE TITLE
JRE is already installed

### ISSUE THREAD

**Issue by CMCDragonkai** [alexkasko/openjdk-unofficial-builds#23]
Is it possible to leave our JRE, since JRE is already installed? The JRE is installed using Oracle's JRE. But this installer insists on installing JRE with the JDK.

**Comment by alexkasko** [comment]
Hi,

On 04/06/2015 06:53 AM, Roger Qiu wrote:
> Is it possible to leave our JRE, since JRE is already installed? The JRE is installed using Oracle's JRE. But this installer insists on installing JRE with the JDK.

No, it is not possible, JRE is mandatory in these installers.

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/openjdk-unofficial-builds/issues/23
>

-- 
-Alex

**Comment by alexkasko** [comment]
Closing this.
