### ISSUE TITLE
Version name difference can cause issues with Android SDK and/or ant

### ISSUE THREAD

**Issue by qubodup** [alexkasko/openjdk-unofficial-builds#25]
When trying to run `ant debug` to build an .apk file with https://bitbucket.org/MartinFelis/love-android-sdl2/ using Android SDK with JAVA_HOME being set to the location of openjdk I get:

<pre>-dex:
      [dex] input: C:\Users\ESP\Desktop\loveToAndroid\loveToAndroid\love-android-sdl2\bin\classes
      [dex] Converting compiled files and external libraries into C:\Users\ESP\Desktop\loveToAndroid
\loveToAndroid\love-android-sdl2\bin\classes.dex...
       [dx]
       [dx] ERROR: No suitable Java found. In order to properly use the Android Developer
       [dx] Tools, you need a suitable version of Java JDK installed on your system.
       [dx] We recommend that you install the JDK version of JavaSE, available here:
       [dx]   http://www.oracle.com/technetwork/java/javase/downloads
       [dx]
       [dx] If you already have Java installed, you can define the JAVA_HOME environment
       [dx] variable in Control Panel / System / Avanced System Settings to point to the
       [dx] JDK folder.
       [dx]
       [dx] You can find the complete Android SDK requirements here:
       [dx]   http://developer.android.com/sdk/requirements.html
       [dx]
       [dx] Error: keywords 'java version' not found in 'openjdk version "1.7.0-u80-unoff'</pre>

I'm not sure what's responsible for this method of identifying JDK. Perhaps it's find_java.bat and the 32bit/64bit exe files near it. Nonetheless it seems that ant and/or Android SDK are affected.

**Comment by alexkasko** [comment]
Hi,

On 07/11/2015 07:12 AM, Iwan Gabovitch wrote:
> When trying to run `ant debug` to build an .apk file with https://bitbucket.org/MartinFelis/love-android-sdl2/ using Android SDK with JAVA_HOME being set to the location of openjdk I get:
>
> <pre>-dex:
>        [dex] input: C:\Users\ESP\Desktop\loveToAndroid\loveToAndroid\love-android-sdl2\bin\classes
>        [dex] Converting compiled files and external libraries into C:\Users\ESP\Desktop\loveToAndroid
> \loveToAndroid\love-android-sdl2\bin\classes.dex...
>         [dx]
>         [dx] ERROR: No suitable Java found. In order to properly use the Android Developer
>         [dx] Tools, you need a suitable version of Java JDK installed on your system.
>         [dx] We recommend that you install the JDK version of JavaSE, available here:
>         [dx]   http://www.oracle.com/technetwork/java/javase/downloads
>         [dx]
>         [dx] If you already have Java installed, you can define the JAVA_HOME environment
>         [dx] variable in Control Panel / System / Avanced System Settings to point to the
>         [dx] JDK folder.
>         [dx]
>         [dx] You can find the complete Android SDK requirements here:
>         [dx]   http://developer.android.com/sdk/requirements.html
>         [dx]
>         [dx] Error: keywords 'java version' not found in 'openjdk version "1.7.0-u80-unoff'</pre>
>
> I'm not sure what's responsible for this method of identifying JDK. Perhaps it's find_java.bat and the 32bit/64bit exe files near it. Nonetheless it seems that ant and/or Android SDK are affected.

If understand the problem correctly, Android SDK tries to parse version 
number from "java -version" output  and fails on "openjdk version 
"1.7.0-u80-unofficial"" string. There is little I can do about this, 
please see the details in this issue - 
https://github.com/alexkasko/openjdk-unofficial-builds/issues/19

PS: for future  versions of OpenJDK such issues are going to be solved 
by Project Verona - http://openjdk.java.net/projects/verona/

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/openjdk-unofficial-builds/issues/25
>


-- 
-Alex

**Comment by alexkasko** [comment]
openjdk-unofficial-builds project is discontinued, closing the issue.
