### ISSUE TITLE
Error when installing 64 bits version in Windows 7

### ISSUE THREAD

**Issue by Petrouchka** [alexkasko/openjdk-unofficial-builds#26]
I installed OpenJDK 7 update 80 build 32 AMD64 on Windows 7, with checking all the options :
![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-1](https://cloud.githubusercontent.com/assets/3955499/10266940/7a5e09c2-6a7d-11e5-89c7-7244aa9b8b60.png)
I installed it as a user with administrator rights :
![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-8](https://cloud.githubusercontent.com/assets/3955499/10266929/18b48872-6a7d-11e5-8496-95a308394107.png)
but I've got these errors :
![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-2](https://cloud.githubusercontent.com/assets/3955499/10266950/8ace8a3e-6a7d-11e5-8f44-642570bcecb6.png)
![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-3](https://cloud.githubusercontent.com/assets/3955499/10266953/9db70b1c-6a7d-11e5-8aa8-aa00b8940207.png)
And then, ArecaBackup did not start :
![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-4](https://cloud.githubusercontent.com/assets/3955499/10266955/b664a66a-6a7d-11e5-9991-a9a1ed0631a5.png)
It's strange because the user was in the administrator group. Then, I installed OpenJDK again, as administrator :
![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-5](https://cloud.githubusercontent.com/assets/3955499/10266957/ebbbc6cc-6a7d-11e5-8cd1-0f580397af5f.png)
I had twice times this error :
![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-6](https://cloud.githubusercontent.com/assets/3955499/10266959/17a43706-6a7e-11e5-9f86-0541011fbefd.png)
But now, Areca Backup starts.

Is it normal that a user in the administrator group can't install OpenJDK ?
Is the error with "pathman.cmd" important ?

**Comment by alexkasko** [comment]
Hi,

On 10/04/2015 08:57 AM, Petrouchka wrote:
> I installed OpenJDK 7 update 80 build 32 AMD64 on Windows 7, with checking all the options :
> ![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-1](https://cloud.githubusercontent.com/assets/3955499/10266940/7a5e09c2-6a7d-11e5-89c7-7244aa9b8b60.png)
> I installed it as a user with administrator rights :
> ![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-8](https://cloud.githubusercontent.com/assets/3955499/10266929/18b48872-6a7d-11e5-8496-95a308394107.png)
> but I've got these errors :
> ![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-2](https://cloud.githubusercontent.com/assets/3955499/10266950/8ace8a3e-6a7d-11e5-8f44-642570bcecb6.png)
> ![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-3](https://cloud.githubusercontent.com/assets/3955499/10266953/9db70b1c-6a7d-11e5-8aa8-aa00b8940207.png)
> And then, ArecaBackup did not start :
> ![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-4](https://cloud.githubusercontent.com/assets/3955499/10266955/b664a66a-6a7d-11e5-9991-a9a1ed0631a5.png)
> It's strange because the user was in the administrator group. Then, I installed OpenJDK again, as administrator :
> ![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-5](https://cloud.githubusercontent.com/assets/3955499/10266957/ebbbc6cc-6a7d-11e5-8cd1-0f580397af5f.png)
> I had twice times this error :
> ![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox-6](https://cloud.githubusercontent.com/assets/3955499/10266959/17a43706-6a7e-11e5-9f86-0541011fbefd.png)
> But now, Areca Backup starts.

In the installer there are two expected installation scenarios:

1) install for current user only without administrator rights

In that case of last three checkboxes only "Set environment variables 
(user settings)" should be checked. It will adjust user (non-global) 
PATH variable using pathman utility (from here [1]) that is run through 
pathman.cmd wrapper [2]. It will also set non-global JAVA_HOME variable. 
In that case applications that expect JAVA_HOME or `java` executable in 
PATH should work. But applications (like launch4j [3]) that read Java 
details from windows registry won't work.

2) install globally

In that case installer must be started as "right click"->"run as 
Administrator". Of last three checkboxes "Set environment variables 
(user settings)" must be unchecked, and two last ones should be checked. 
I am not sure what exactly will happen if you will try to adjust both 
user and global PATH variable, but it is a bad idea for sure. Global 
PATH and JAVA_HOME are adjusted using exactly the same pathman.cmd 
method as a local ones. In windows registry some keys will be added to 
HKEY_LOCAL_MACHINE/Software/JavaSoft/Java Runtime Environment/1.7 path 
using %WINDIR%/system32/reg.exe utility. There is a caveat here when you 
want to install x86 openjdk on x86_64 windows - x86_64 windows has 
separate registry subtree for x86 applications. It should work 
transparently for the applications like launch4j, though. I can confirm 
that registry settings will allow launch4j-wrapped applications to run - 
checked this with muCommander [4].

>
> Is it normal that a user in the administrator group can't install OpenJDK ?

I think it is better to use "right click"->"run as Administrator" every 
time you want to do a global install. It is easy to make install.exe 
launcher to request administrator rights all the time (this won't allow 
user-local installs though), but it is tricky to request such rights 
"on-demand" from installer itself.

> Is the error with "pathman.cmd" important ?

It means that PATH and/or JAVA_HOME variables adjustment failed, just 
check these variables for the results.

Hope this helps.

[1] https://support.microsoft.com/en-us/kb/927229
[2] 
https://github.com/alexkasko/openjdk-unofficial-builds/blob/openjdk7/installer/windows-amd64/uninstall/tools/pathman.cmd
[3] http://launch4j.sourceforge.net/
[4] http://www.mucommander.com/

-- 
-Alex

**Comment by Petrouchka** [comment]
When I'm installing Java from java.com, I don't have all these problems. Isn't it possible to use the same installation method for OpenJDK ? OpenJDK is simple to install on Windows XP but too complicated to install on 7 for a normal user.

**Comment by alexkasko** [comment]
On 10/04/2015 09:57 AM, Petrouchka wrote:
> When I'm installing Java from java.com, I don't have all these problems. Isn't it possible to use the same installation method for OpenJDK ?

Oracle installer is not open-source, so the same installation logic 
should be reimplemented.

> OpenJDK is simple to install on Windows XP but too complicated to install on 7 for a normal user.

If normal user doesn't have administrator rights (or doesn't need global 
install) this installer should work fine with normal double-click run 
and all options by default. This is a main expected mode for this installer.

Complications arise when the user wants to make changes to registry. I 
think for such use-case (when user always wants global install) it is 
better to have a separate installer bundle that will request admin 
rights (through UAC dialog) automatically on start and global PATH and 
registry checkboxes will be set by default. I experimented with this 
mode and it worked fine, but of course I cannot publish two sets of 
installers.

If you will be interested in building such installer yourself (from 
plain zip openjdk) - I can share the details, enhanced install.exe 
launcher and an izpack config.

-- 
-Alex

**Comment by Petrouchka** [comment]
"If normal user doesn't have administrator rights (or doesn't need global install) this installer should work fine with normal double-click run and all options by default." : indeed, in this case, OpenJDK 7 update 80 build 32 AMD64 on Windows 7 is installed without an error message but after, Areca Backup doesn't work, I suppose it needs an installation with changes in the registry :
![capture-clone de windows 7 professionnel instantane 1 en fonction - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/3955499/10267189/79dd7a5c-6a8a-11e5-92d9-416c016eb142.png)
So, the ideal solution is an installer bundle that will request admin rights (through UAC dialog) automatically on start and global PATH and registry checkboxes will be set by default but I'm not enough good to build it.

**Comment by alexkasko** [comment]
openjdk-unofficial-builds project is discontinued, closing the issue.

**Comment by InfoLibre** [comment]
It would be interesting to collaborate with Zulu for ojdkbuild.
https://www.azul.com/products/zulu/

**Comment by alexkasko** [comment]
Hi,

On 04/30/2016 10:25 PM, Petrouchka wrote:

> It would be interesting to collaborate with Zulu for ojdkbuild.
> https://www.azul.com/products/zulu/

I commented on Zulu builds before here - 
https://github.com/alexkasko/openjdk-unofficial-builds/issues/17#issuecomment-165096258

Some kind of collaboration is going on through upstream OpenJDK project, 
for example this bug - https://bugs.openjdk.java.net/browse/JDK-8133206 
, was fixed in Zulu first and then published to OpenJDK and included 
into ojdkbuild. And this bug 
https://bugs.openjdk.java.net/browse/JDK-8153925 was fixed in ojdkbuild 
first and will likely be included into other OpenJDK distributions soon.

I doubt that any direct collaboration is possible/needed here, as goals 
(and also scope and size) of the projects are quite different.

## 

-Alex
