### ISSUE TITLE
Double-Clicking on .jar files in Windows

### ISSUE THREAD

**Issue by NTICompass** [alexkasko/openjdk-unofficial-builds#27]
I installed OpenJDK x64 on Windows 10 Pro (64-bit).  When I double-clicked on a .jar file, Windows asked me to find a program to open it.

Can this registry key be added to the installer?

P.S. I managed to fix it by running the following in an Administrator command prompt:

```
$ assoc .jar=jarfile
$ ftype jarfile="C:\OpenJDK\jre\bin\javaw.exe" -jar "%1" %*
```

**Comment by alexkasko** [comment]
Hi,

On 12/22/2015 05:23 PM, Eric Siegel (Rocket Hazmat) wrote:
> I installed OpenJDK x64 on Windows 10 Pro (64-bit)  When I double-clicked on a jar file, Windows asked me to find a program to open it
>
> Can this registry key be added to the installer?

Installer supports registry keys when running "As Administrator". Please 
see this issue for details - 
https://github.com/alexkasko/openjdk-unofficial-builds/issues/26

>
> PS I managed to fix it by running the following in an Administrator command prompt:
>
> ```
> $ assoc jar=jarfile
> $ ftype jarfile="C:\OpenJDK\jre\bin\javawexe" -jar "%1" %*
> ```
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/openjdk-unofficial-builds/issues/27
>


-- 
-Alex

**Comment by alexkasko** [comment]
openjdk-unofficial-builds project is discontinued, closing the issue.
