### ISSUE TITLE
Build should be stripped (optionally) and contain no debug symbols or maps

### ISSUE THREAD

**Issue by pombredanne** [alexkasko/openjdk-unofficial-builds#3]
The windows builds contain .pdb and .map files
Elfs are not stripped

This can probably make the builds much slimmer

**Comment by NN---** [comment]
Is it possible to have pdb file and not the 'diz' file ?
Thanks

**Comment by alexkasko** [comment]
Hi,

On 12/15/2015 08:30 PM, NN wrote:
> Is it possible to have pdb file and not the 'diz' file ?

I never used these debug files myself but AFAIK these DIZ files are just 
ZIP archives containing (on windows) PDBs and some other stuff. At least 
I can see jvm.pdb and jvm.map inside jvm.diz.

> Thanks
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/openjdk-unofficial-builds/issues/3#issuecomment-164887694
>


-- 
-Alex

**Comment by NN---** [comment]
At first glance I didn't understand what it is.
After opening file in editor I noticed PK so it is easy to unzip it.

The only problem that debuggers don't understand 'diz' flies, they know pdb.
